let myDate = new Date()
console.log(myDate.toString())
console.log(myDate.toDateString())
console.log(myDate.toISOString())
console.log(myDate.toJSON())
console.log(myDate.toLocaleDateString())
console.log(myDate.toLocaleString())
console.log(typeof myDate)

let myCreateDate = new Date(2025,1,5)
console.log(myCreateDate.toDateString())
let myCreatedDate = new Date("2025-02-05")
console.log(myCreatedDate.toLocaleString())
let myTimeStamp = Date.now()
console.log(myTimeStamp)
console.log(myCreateDate.getTime())
console.log(Math.floor(Date.now()/1000))

let newDate = new Date ()
console.log(newDate.getDate())
console.log(newDate.getDay())
console.log(newDate.getFullYear())
console.log(newDate.getHours())

newDate.toLocaleString ('Default',{weekday: "long" })